// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// ToastContainer renders the toast notification container with client-side JS
// that listens for HTMX HX-Trigger response headers and displays toast notifications.
func ToastContainer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"toast-container\" class=\"fixed bottom-4 right-4 z-50 space-y-2\"></div><script>\n\t\t(function() {\n\t\t\tvar container = document.getElementById('toast-container');\n\t\t\tif (!container) return;\n\n\t\t\t// Color map for toast levels\n\t\t\tvar levelStyles = {\n\t\t\t\tsuccess: 'bg-green-500',\n\t\t\t\terror:   'bg-red-500',\n\t\t\t\twarning: 'bg-yellow-500'\n\t\t\t};\n\n\t\t\t// Show a toast notification with auto-dismiss\n\t\t\tfunction showToast(message, level) {\n\t\t\t\tlevel = level || 'error';\n\t\t\t\tvar bgClass = levelStyles[level] || 'bg-red-500';\n\n\t\t\t\tvar toast = document.createElement('div');\n\t\t\t\ttoast.className = bgClass + ' text-white px-4 py-3 rounded shadow-lg opacity-0 transition-opacity duration-300';\n\t\t\t\ttoast.textContent = message;\n\t\t\t\tcontainer.appendChild(toast);\n\n\t\t\t\t// Fade in\n\t\t\t\trequestAnimationFrame(function() {\n\t\t\t\t\ttoast.style.opacity = '1';\n\t\t\t\t});\n\n\t\t\t\t// Auto-dismiss after 4 seconds\n\t\t\t\tsetTimeout(function() {\n\t\t\t\t\ttoast.style.opacity = '0';\n\t\t\t\t\tsetTimeout(function() {\n\t\t\t\t\t\tif (toast.parentNode) {\n\t\t\t\t\t\t\ttoast.parentNode.removeChild(toast);\n\t\t\t\t\t\t}\n\t\t\t\t\t}, 300);\n\t\t\t\t}, 4000);\n\t\t\t}\n\n\t\t\t// Listen for HTMX afterRequest events\n\t\t\tdocument.addEventListener('htmx:afterRequest', function(e) {\n\t\t\t\tvar xhr = e.detail.xhr;\n\t\t\t\tif (!xhr) return;\n\t\t\t\tvar trigger = xhr.getResponseHeader('HX-Trigger');\n\t\t\t\tif (!trigger) return;\n\t\t\t\ttry {\n\t\t\t\t\tvar data = JSON.parse(trigger);\n\t\t\t\t\tshowToast(data.message, data.level || 'error');\n\t\t\t\t} catch(err) {\n\t\t\t\t\t// Non-JSON trigger header — ignore\n\t\t\t\t}\n\t\t\t});\n\n\t\t\t// Expose for manual use\n\t\t\twindow.showToast = showToast;\n\t\t})();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
